name: Thowhith-pipeline

on: workflow_dispatch

jobs:
  Thowhith-job:
    runs-on: ubuntu-latest
    steps:
     - name: print my name
       run: echo "Mohamed Thowhith"
     - name: install python
       uses: actions/setup-python@v6
       with:
         python-version: '3.10'
     - name: check python version
       run: python --version
